# Configuration
config:
  # MD013 - line-length
  line_length:
    line_length: 120
    code_blocks: false
    tables: false
  html:
    allowed_elements:
      - div

# Globs
globs:
  - "**/*.md"
  - "**/*.markdown"

# Ignores
ignores:
  - "*.svg"

# Fix any fixable errors
fix: true
